---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgAYrqHed6I0y2q40gCww7zMw0KtOk92RKUc6B8d+67kDvSLgdlv5u3Jt2KIR9FjUsSySjpbAEWh8r5Kj+UpNvlQzlvUfdIfHaoNFwMV9ahBAznDSYAOQ5sdt7zXCnI2OK6WuffT6RKW0SXvXQC/MdzuHx2gkRLPrL4HNmnLRo122GN8Jnf+HFlHKwtH3ZOyHO8WV4iSzB2NA4nbrqyw3NLB6Gnp/Y7zS38KlImyChIRmKfG8kYuZzOyatOrsXZmxCzogYIc7OpLFVMr89o83OYu3hgIZLjU0+T0FGycGEXIgx+Qgyj/dxqUxPusx11iMT93FgMLjpIeQnSq7tVYjkUk35BzZn2p2x+ej/UN8T7Kq1rT1azxNWMOY8E0kadXr8WK/HGNqGvM5tmS2sGCD2+hOMowKRniatccLSz+fCCUoczQc0ZGNvomB0mCCRzQNgHV6UybbEV2ARAA3Vl5/EwXDwWj6/NhJFgE0d71vS5MrLa8G2c521+n+6EFaFWP2aR/mBJd5yHZYtKS7bE5g/1NSz7cdBbcJpctFw0EtA3d80YbzTDuE9O1pL/V1Z8DWPJtQcnnKGquVQSExBTbxrk0XP4yEVH2dWE/Dy9iTDqyXkC0inj86wczzJSShRqgGoqFh4fQyCSHjhJM0DuWQHGRvPLwO245ZxT2b4ZAU2tCBbiC3Ta+eqv/E+JK0vCjxsI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token
