apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-integration-server
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem